version: '3.1'

services:

  db:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
  
    volumes:
      - $PWD/data:/var/lib/mysql
      - $PWD/my.cnf:/etc/mysql/my.cnf

  adminer:
    image: adminer
    restart: always
    ports:
      - 3307:8080