version: "3"

services:
  grafana:
    image: grafana/grafana-oss
    volumes:
      - $PWD/grafana/volume:/var/lib/grafana
    ports:
      - 8087:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: password