version: "3"
services:
  kafka1:
   image: 'bitnami/kafka:latest'
   network_mode: kafka-cluster
   container_name: kafka11
   user: root
   ports:
    - 9192:9092
    - 9193:9093
   environment:
   
    - KAFKA_ENABLE_KRAFT=yes

    - KAFKA_CFG_PROCESS_ROLES=broker,controller
   
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
   
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
   
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
   
    - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
 
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka11:9093,2@kafka22:9093,3@kafka33:9093
   
    - ALLOW_PLAINTEXT_LISTENER=yes
 
    - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M 
 
    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false


    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://128.195.151.182:9192

    - KAFKA_BROKER_ID=1

    - KAFKA_CFG_NODE_ID=1
   volumes:
    - $PWD/data1:/bitnami/kafka
  #extra_hosts:
   #- "kafka1:????IP"
   #- "kafka2:????IP"
   #- "kafka3:????IP"
  kafka2:
   image: 'bitnami/kafka:latest'
   network_mode: kafka-cluster
   container_name: kafka22
   user: root
   ports:
    - 9292:9092
    - 9293:9093
   environment:

    - KAFKA_ENABLE_KRAFT=yes

    - KAFKA_CFG_PROCESS_ROLES=broker,controller

    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093

    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT

    - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA

    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka11:9093,2@kafka22:9093,3@kafka33:9093
 
    - ALLOW_PLAINTEXT_LISTENER=yes
 
    - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M 

    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false

    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://128.195.151.182:9292

    - KAFKA_BROKER_ID=2

    - KAFKA_CFG_NODE_ID=2
   volumes:
    - $PWD/data2:/bitnami/kafka
  kafka3:
   image: 'bitnami/kafka:latest'
   network_mode: kafka-cluster
   container_name: kafka33
   user: root
   ports:
    - 9392:9092
    - 9393:9093
   environment:

    - KAFKA_ENABLE_KRAFT=yes

    - KAFKA_CFG_PROCESS_ROLES=broker,controller

    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

    - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
 
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
 
    - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA

    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka11:9093,2@kafka22:9093,3@kafka33:9093

    - ALLOW_PLAINTEXT_LISTENER=yes

    - KAFKA_HEAP_OPTS=-Xmx512M -Xms256M 

    - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false


    - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://128.195.151.182:9392

    - KAFKA_BROKER_ID=3
    - KAFKA_CFG_NODE_ID=3
   volumes:
    - $PWD/data3:/bitnami/kafka