version: "3.7"

services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    #  start redis in persistent storage mode
    volumes:
      - $PWD/redis_data:/data 
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379 # Localhost:container_name:port
      - HTTP_USER=root
      - HTTP_PASSWORD=123456
     # protect redis commander interface with login/password
    ports:
      - 8081:8081
    depends_on: #  prevents container to start before other container, on which it depends
      - redis